export const INIT_MENU = 'INIT_MENU';
export const MENU_RECEIVED = 'MENU_RECEIVED';
export const ORDERED_ITEMS_COUNT_CHANGED = 'ORDERED_ITEMS_COUNT_CHANGED';
export const ORDER_SENT_SUCCESS = 'ORDER_SENT_SUCCESS';